language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pseemangal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pseemangal/react-test npm test

after_success:
  - docker build -t pseemangal/multi-client ./client
  - docker build -t pseemangal/multi-nginx ./nginx
  - docker build -t pseemangal/multi-server ./server
  - docker build -t pseemangal/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to docker hub
  - docker push pseemangal/multi-client
  - docker push pseemangal/multi-nginx
  - docker push pseemangal/multi-server
  - docker push pseemangal/multi-worker